export const USER_SIGNUP_REQUEST = 'USER_CREATE_REQUEST';
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';

export const USER_LOGUOT_REQUEST = 'USER_LOGUOT_REQUEST';
export const USER_LOGUOT_FAILED = 'USER_LOGUOT_FAILED';
export const USER_LOGUOT_SUCCESS = 'USER_LOGUOT_SUCCESS';
