export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_FAILED = 'USER_CREATE_FAILED';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';

export const USER_RELOAD_REQUEST = 'USER_RELOAD_REQUEST';
export const USER_RELOAD_FAILED = 'USER_RELOAD_FAILED';
export const USER_RELOAD_SUCCESS = 'USER_RELOAD_SUCCESS';

export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST';
export const USER_RESET_PASSWORD_FAILED = 'USER_RESET_PASSWORD_FAILED';
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS';

export const USER_LOGUOT_REQUEST = 'USER_LOGUOT_REQUEST';
export const USER_LOGUOT_FAILED = 'USER_LOGUOT_FAILED';
export const USER_LOGUOT_SUCCESS = 'USER_LOGUOT_SUCCESS';
